version: '3'
services:
  db-event-service:
    image: postgres:12
    restart: always
    ports:
      - 5446:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: event-service