version: '3'
services:
  eureka-api:
    image: eureka-api:1.0.1
    container_name: eureka-api
    build:
      context: .
    ports:
      - 8010:8010
    networks:
      - sueta_network

networks:
  sueta_network:
    name: sueta_network
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16