version: '3'
services:
  db-file-service:
    image: postgres:12
    restart: always
    ports:
      - 5447:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: file-service

  file-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8052:8052