version: '3'
services:
  db-client-service:
    image: postgres:12
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: client-service


  client-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8051:8051